{% set version = "2.7" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: ad282f9b6926286d2ead4750552c8a6142bc4c783fd66b0293547c8fe6ae126a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - beautifulsoup4
    - python {{ python_min }}
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup

extra:
  recipe-maintainers:
    - MementoRC
    - jschueller
