{% set version = "2.6" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: e2e68417777af359ec65daac1057404a3c8a5455bb8abc36f1a9866ab1a51abb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - beautifulsoup4
    - python {{ python_min }}
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup

extra:
  recipe-maintainers:
    - MementoRC
    - jschueller
